### ISSUE TITLE
Set up cloudinary AI

### ISSUE THREAD

**Issue by hrit2773** [hrit2773/Imagify-SaaS-Frontend#1]
Get the API key for cloudinary AI image transformation and set up the environment

**Comment by Moses-Padirolu** [comment]
Okay , i'll do.

**Comment by hrit2773** [comment]
@Moses-Padirolu you can go ahead with the PR

**Comment by Moses-Padirolu** [comment]
@hrit2773 its done, i sent you pull request , verify it .

**Comment by hrit2773** [comment]
https://github.com/hrit2773/Imagify-SaaS-Frontend/pulls
